### ISSUE TITLE
Failed to install due to invalid structure

### ISSUE THREAD

**Issue by cw-kid** [winsomehax/plugin.video.bitchute#19]
Running LibreElec Kodi 18.9 Leia the downloaded .zip file is 210KB from the Master branch.

I downloaded it a second time but still get the same error. 

I then tried the zip file from the Testing branch instead and that installed OK.

Also is there a Kodi Repo for this add-on so it is kept up to date ? 

Thanks

**Comment by winsomehax** [comment]
You see this message if you try to install the add-on again without restarting KODI in between.

The structure of the zip file appears to be fine - I've installed it myself.

As for a repo... happy to accept patches etc from people who want to do that.

**Comment by cw-kid** [comment]
OK thanks. 

I was installing and uninstalling various different forks of this add-on so maybe that was the problem. 

I am running your Testing branch version currently OK.

I will try the main Master version again later. 

Cheers.

**Comment by winsomehax** [comment]
N/A
