### ISSUE TITLE
Login does not seem to work

### ISSUE THREAD

**Issue by cmF3** [winsomehax/plugin.video.bitchute#22]
To reproduce:

1) Get bitchute account and subscribe to any channel
2) Install plugin.video.bitchute and enter your bc account credentials
3) In BC-Plugin menu select Subscriptions
4) Observe: ***YOU HAVE NO SUBSCRIPTIONS***
5) Select any other other account related menu item and observe the same

Should display: BC Subscriptions
Error: None
Error in Logs (with --debug): None
Note: Using Kodi19

**Comment by winsomehax** [comment]
I've refreshed the KODI 19 branch from master. Give it another try.

FYI. The only difference needed for KODI 19 is change to the addon.xml file to say it requires python 3.0.0. I'd let the branch slip a bit.

**Comment by cmF3** [comment]
Yup, works now. Thanks.
