### ISSUE TITLE
test on Kodi 19.0 with libreelec nightly builds

### ISSUE THREAD

**Issue by Isayso** [winsomehax/plugin.video.bitchute#36]
I use the libeelec 10.0 nightly builds on RPi 3+ and I want to send plugin: commands to your bitchute addon.

Unfortunately I cannot run any Video, even not with the "Open by ID" menu. I don't have a Bitchute login so far, the "Popular" or "Trending" menu says "unable to login" and shows nothing. 

Please can you give me the right syntax for the plugin string to send via http POST ?
e.g. "plugin://plugin.video.bitchute/video/" +ID  (does not work)

Thanks!

**Comment by QNET17** [comment]
+1

**Comment by Isayso** [comment]
I found the working plugin string now

"plugin://plugin.video.bitchute/play_now/" +ID   but works only with login, an entry point without login would be nice.

**Comment by winsomehax** [comment]
I've updated the "test" branch to remove the login check for open a video. give it a a try and let me know what happens

P.S. I've no way to test anything but KODI 19 now so the old stuff will be unmaintained soon

**Comment by Isayso** [comment]
I just copied the changed file to the plugin.video.bitchute folder on Raspberry, deleted my login and did a short test run.
Looks good! 
Thanks!

**Comment by winsomehax** [comment]
Good. If it's all working close this and i will promote it from testing to master and kodi 19 branches
