### ISSUE TITLE
Plugin does not respect Content Sensitivity Setting

### ISSUE THREAD

**Issue by cmF3** [winsomehax/plugin.video.bitchute#44]
Bitchute has an annoying NSFW/NSFL filter feature at Settings -> Interface -> Content Sensitivity. Regardless of what is set there, videos set to NSFW/NSFL do not show up in any listings and cannot be searched for in the plugin.

Ideally, the plugin should just display all videos and ignore the filter.

**Comment by winsomehax** [comment]
That's odd. The plugin logs into your account and just does a search like a webbrowser would - meaning it should just return any video you would get normally according to your settings.

Do you have a particular example of a video being ignored in search that I could have a look at to see what's going back/forth.

**Comment by cmF3** [comment]
It took me some time to find a good example, but I think I have found one. It turns out this may be an issue with bitchute search so I am not sure how much you can do about it.

This video can be searched for (I used the search term "ninja scroll") and it shows up in the website and in the plugin and is not tagged NSFW: https://www.bitchute.com/video/njPOWE7LsEDd/

This video with approx. the same title does not show up in bitchute search (website & plugin), and I can only guess it is because it's tagged NSFW: https://www.bitchute.com/video/2VsM5XxFdHpx/

I am not aware of an "unlist from search" feature on bitchute.

**Comment by winsomehax** [comment]
if you find it's an issue with the plugin let me know. until then I'll close this.
