### ISSUE TITLE
Can no longer list or play videos

### ISSUE THREAD

**Issue by TK5000** [winsomehax/plugin.video.bitchute#51]
Regardless if I use my login credentials, I can no longer list or play videos.   Trending, Popular, etc are all empty.

Error: "Login failed, Unable to login to Bitchute with the details provided".

I've logged out, logged back in, and tried without a login.  Also uninstalled and reinstalled and found no solution.  I've been using this addon for over a year and it's been running perfectly until now.

I'm running Kodi 19 Matrix and haven't upgraded anything (that I know of) which would break the addon.

**Comment by DavidFW1960** [comment]
That's odd. My subscriptions are all still listed correctly....

**Comment by TK5000** [comment]
> That's odd. My subscriptions are all still listed correctly....

I had an old Raspberry Pi 3 laying around, so I tried a clean build.

LibreELEC 11.0
Kodi 20.1
Linux Kernel 6.1.x

The only thing I did was enable SSH and install the Bitchute addon.  I have the same issue.

**Comment by TK5000** [comment]
I tried an older build and had the same issue.

old Version (2023.01)
LibreELEC 10.0
Kodi 19.5
Linux Kernel 5.10.x

**Comment by TK5000** [comment]
I was able to solve the issue by using a new build, setting the user/pass, then entering the "subscriptions" page to force a login.  After that, other pages like popular and trending work again.  No pages will work unless you force a login.
