### ISSUE TITLE
Bitchute addon dead for now.

### ISSUE THREAD

**Issue by stwubby** [winsomehax/plugin.video.bitchute#52]
When you go to subscribed channel all videos are saying "error parsing" Only videos that play are popular and trending.

**Comment by vigilant4u** [comment]
Here the same. The plugin needs to be fixed please. I am using it with Matrix 20.2 But it does not PARSE ANY MORE since October 27th, 2023. ThxWinSomeHax for your bugfix and support

**Comment by SethEddy** [comment]
bitchute_access.py
line 409
`date=n.find(class_="channel-videos-details").find("span").get_text()`
needs to be
`date=n.find(class_="channel-videos-details").find("p").get_text()`
I also changed line 412
`description = n.find(class_="channel-videos-text").get_text()`
to
`description = n.find(class_="channel-videos-text").find("p").get_text()`
got me back and running.

**Comment by vigilant4u** [comment]
> bitchute_access.py
> line 409
> `date=n.find(class_="channel-videos-details").find("span").get_text()`
> needs to be
> `date=n.find(class_="channel-videos-details").find("p").get_text()`
> I also changed line 412
> `description = n.find(class_="channel-videos-text").get_text()`
> to
> `description = n.find(class_="channel-videos-text").find("p").get_text()`
> got me back and running.

Thx  a lot SethEddy. I will try your code changes tonight. Best Vigilante

**Comment by vigilant4u** [comment]
> > bitchute_access.py
> > line 409
> > `date=n.find(class_="channel-videos-details").find("span").get_text()`
> > needs to be
> > `date=n.find(class_="channel-videos-details").find("p").get_text()`
> > I also changed line 412
> > `description = n.find(class_="channel-videos-text").get_text()`
> > to
> > `description = n.find(class_="channel-videos-text").find("p").get_text()`
> > got me back and running.
> 
==> Thx a lot SethEddy. YOur code adoption worked perfectly This for keeping Bitchute in Kodi alive. 
Best Vigilante

T

**Comment by winsomehax** [comment]
Yes. Thank you for submitting a fix. I have virtually no free time these days. If you would like to do it as a pull request I will merge it in, or I will do it manually when I get a minute.

Thanks again.

**Comment by stwubby** [comment]
Me too give thanks for that code sleuthing. Worked great. Did notice though some videos audio drops out and video locks up and shows still image for a few seconds then starts playing again. Probably not related to this fix. Only some channels and not others. Merging with a new version would be good for those not savey enough to even find those hidden folders. 
Thanks again SethEddy. One thing I would love to see but don't have the python or any code smarts for would be, to have the title of the video show instead of random characters of the bitchute video name. I believe that used to be the case in a much earlier bitchute version which makes saving a downloaded video a lot more streamlined.

**Comment by winsomehax** [comment]
Would anyone like to checkout the Testing branch and try it. The changes suggested by SethEddy have been merged into that branch. Let me know if it works... and if it does I will move them to the master branch

**Comment by DavidFW1960** [comment]
I will.

**Comment by DavidFW1960** [comment]
OK seems to be working ok for me. Thanks

**Comment by winsomehax** [comment]
> OK seems to be working ok for me. Thanks

Merged into master. Thanks again, @SethEddy

**Comment by coffseducation** [comment]
Where in the filesystem is bitchute_access.py?
I cannot locate it. : (

**Comment by winsomehax** [comment]
If you are looking to get this working after the fix, you should download the zip (see readme) from the master branch and install the add-on again.

**Comment by coffseducation** [comment]
Yes, thank you that worked.
