### ISSUE TITLE
Subscriptions FAIL after successfully setting my bitchute user login data (being saved in userdata ../settings)

### ISSUE THREAD

**Issue by vigilant4u** [winsomehax/plugin.video.bitchute#9]
SEE THE LOG:

2020-12-18 10:32:25.033 T:123145546637312   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get_text'
                                            Traceback (most recent call last):
                                              File "/Users/me/Library/Application Support/Kodi/addons/plugin.video.bitchute/main.py", line 4, in <module>
                                                kodi_bitchute.plugin.run()
                                              File "/Users/me/Library/Application Support/Kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/Users/me/Library/Application Support/Kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/Users/me/Library/Application Support/Kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 42, in subscriptions
                                                build_subscriptions()
                                              File "/Users/me/Library/Application Support/Kodi/addons/plugin.video.bitchute/kodi_bitchute.py", line 140, in build_subscriptions
                                                subscriptions = store.bitchute.get_subscriptions()
                                              File "/Users/me/Library/Application Support/Kodi/addons/plugin.video.bitchute/bitchute_query.py", line 108, in get_subscriptions
                                                last_video = sub.find(class_="subscription-last-video").get_text()
                                            AttributeError: 'NoneType' object has no attribute 'get_text'
                                            -->End of Python script error report<--

Please be so kind and fix this as soon as possible. THe other feature do work as described in your readme ;)
Best Vigilant

**Comment by winsomehax** [comment]
I've published a new branch for this repo called "Fixes". I suspect (guess!) that the error was because one of your subscriptions on Bitchute didn't have a last-video entry. It wasn't used anyway so I've removed the line scraping it from the website.

Can you try using the "Fixes" branch please, before I push it to main so everyone gets it.

Many thanks for reporting this.

**Comment by vigilant4u** [comment]
> I've published a new branch for this repo called "Fixes". I suspect (guess!) that the error was because one of your subscriptions on Bitchute didn't have a last-video entry. It wasn't used anyway so I've removed the line scraping it from the website.
> 
> Can you try using the "Fixes" branch please, before I push it to main so everyone gets it.
> 
> Many thanks for reporting this.

------
THE GOOD NEWS FIRST:
1) Your fix in "bitchute_query.py" did work. Now the subscripted channel names are viewable and with a click inside the videos from the authors do work! SO you can copy your fix back to the main branch.
 
THE BAD NEWS: 
In your alpha version "subscriptions" was comparable with the youtube plugins function "My subscriptions". Here you were able to see all the videos from the subscribed authors from top to button, newest first, oldest last. Now with your version 1.0 after your alpha version that function is not there at all. Can you please bring it back so that anybody is able to see all videos from newest to oldest instead of just seeing the names of your subscribed authors or better: Make a new topic called "my subscribed videos" or sth. PLEASE BRING BACK THE MAIN KILLER FEATURE FUNCTION as this makes your plugin the most valuable. Best VIGILANT.

**Comment by winsomehax** [comment]
I'm a bit confused. On the "Fixes" branch... If you open the add-on and then "Subscriptions" you should see a list of channels you are subscribed to. If you then select one of those channels you should see a list of videos available on that channel - and then select any of those videos to watch.
That works here. If it's doing something different for you can you send another log please.

**Comment by vigilant4u** [comment]
> I'm a bit confused. On the "Fixes" branch... If you open the add-on and then "Subscriptions" you should see a list of channels you are subscribed to. If you then select one of those channels you should see a list of videos available on that channel - and then select any of those videos to watch.
> That works here. If it's doing something different for you can you send another log please.

---
It is exactlky what your are writing. So the bug is fixed as i wrote in 1)
but what i meant was inseatd of seeing your subscribed channels, why no bringing back the function of seeing all the videos from your subscribed channels , the newest on top the oldest on the button.
Now you always need to click any any of your subscrbed channels and manually see whether there is a new video. I WANT YOU TO SHOW UP ALL VIDEOS FROM ALL OF YOUR SUBSCRIBED CHANNELS NEWEST ON TOP, understood pal? Best VIGILANT.

**Comment by winsomehax** [comment]
Even the early versions didn't go through the subscriptions like that... the notifications option did/does something like that. There's also popular and trending.

I will have a think about how to to implement something like YouTube's feed.

**Comment by vigilant4u** [comment]
> Even the early versions didn't go through the subscriptions like that... the notifications option did/does something like that. There's also popular and trending.
> 
> I will have a think about how to to implement something like YouTube's feed.

---
Please do implement that killer feature as i am 100% bitchute alpha had that feature as i was using it EVERY SINGLE DAY since May and i am sure i am not hallucinating ;) Best VIGILANT.

**Comment by winsomehax** [comment]
I'm sure you were using something since May, but it wasn't this plugin. I only created it a couple of weeks ago.

I will take a look at implementing a feed over Christmas. 

Thanks

**Comment by vigilant4u** [comment]
> I'm sure you were using something since May, but it wasn't this plugin. I only created it a couple of weeks ago.
> 
> I will take a look at implementing a feed over Christmas.
> 
> Thanks

---

Thx so much in Advance. This would be the best Xmas present by far ;) Best VIGILANT.

**Comment by winsomehax** [comment]
I've done a pretty large refactor of the code and adding in caches to make it faster, also a feed option. The feed option reads through each of your subscribed channels - taking the most recent one from each channel and making one view. It's a little slow as it has to read and process every subscribed channel's page... but it's the only way to provide some kind of feed at the moment. All of these changes are sitting in the Fixes branch if you want to give it a try and let me know if it works.

**Comment by winsomehax** [comment]
Fixes moved to the master branch. Closing issue as bug fixed and enhancement implemented.
